### ISSUE TITLE
AustralianPrisonPopulation.ipynb's base predictions difference vs hts example

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/hierarchicalforecast#100]
The fable/hts [replication 2 notebook](https://nixtla.github.io/hierarchicalforecast/examples/australianprisonpopulation.html), has different base predictions compared to the 
Australian Prison Population example from this [hts example](https://otexts.com/fpp3/prison.html).

Two ideas come to my mind:
- Different data sources
- Different ETS model execution.

**Comment by elephaint** [comment]
The latter (different AutoETS model execution) causes this. As overall the results for the example are satisfyingly comparable (and in fact our bottom predictions with AutoETS are slightly better than fpp3), I'm ok with the difference.
