### ISSUE TITLE
Bug in the README example

### ISSUE THREAD

**Issue by jwang-paradise** [Nixtla/hierarchicalforecast#13]
The example ([_How to use_](https://github.com/Nixtla/hierarchicalforecast/blob/main/README.md#-how-to-use)) in README.md loads data with 
```
Y_df, S, tags = HierarchicalData.load('./data', 'TourismLarge')
```
However the `HierarchicalData.load` method returns a tuple of only 2, causing **not enough values to unpack**.  ([source here](https://github.com/Nixtla/datasetsforecast/blob/a7e6e801aeca367d0a35cf58db9c84ac86c0fb1b/datasetsforecast/hierarchical.py#L107))

Python error message:
```
Traceback (most recent call last):
  File "hierarchicalforecast/example.py", line 11, in <module>
    Y_df, S, tags = HierarchicalData.load('./data', 'TourismLarge')
ValueError: not enough values to unpack (expected 3, got 2)
```

It would also be great if more examples can be provided. 

Thanks!

**Comment by FedericoGarza** [comment]
Hi! :D

Thank you for letting us know about the problem. We recently released new versions of `datasetsforecast` and `hierarchicalforecast` that solve the issue. You can find a colab example here: https://github.com/Nixtla/hierarchicalforecast/blob/main/examples/TourismSmall.ipynb.
