### ISSUE TITLE
Saved Prefitted ARIMA Base Forecasts for TourismL

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/hierarchicalforecast#136]
It would be convenient to have prefitted ARIMA base forecasts for medium and large datasets on S3.
- We guarantee replicability.
- We can save a lot of time for potential users and other researchers.
- Circle CI tests that check time efficiency can greatly benefit from this dataset.

**Comment by mergenthaler** [comment]
Ref: https://github.com/Nixtla/hierarchicalforecast/pull/135/files#diff-9251a1f7e1aeadc509ccf4c1305ff2e7f64d179a5031eb36dbf1839955faa61b

**Comment by elephaint** [comment]
I'm ok with the current behaviour, as the entire notebook runs in a matter of seconds.
