### ISSUE TITLE
Hierarchical forecasting on custom data and `aggregate` function

### ISSUE THREAD

**Issue by alishametkari** [Nixtla/hierarchicalforecast#149]
I want to use hierarchical forecasting for my dataset which is not part of datasetsforecast. I am not sure how can I use any other dataset. How to get summing matrix if we are using some other dataset? 
can anyone help.

**Comment by kdgutier** [comment]
Hi @alishametkari, 

Here is a tutorial where we explain the creation of the series and aggregation matrix:
https://nixtla.github.io/hierarchicalforecast/examples/introduction.html

**Comment by alishametkari** [comment]
Thanks! It helped me.
