### ISSUE TITLE
Easy way to produce the `S_df` dataframe

### ISSUE THREAD

**Issue by ngupta23** [Nixtla/hierarchicalforecast#153]
In the examples you have shown, the dataset is already curated. I was wondering if there is a convenience function that is available to produce the S matrix from new data (assuming for example, that the hierarchy is available in the form of a pandas data frame)?

- https://github.com/Nixtla/hierarchicalforecast#readme 
- https://colab.research.google.com/github/nixtla/hierarchicalforecast/blob/main/nbs/examples/TourismSmall.ipynb

**Comment by kdgutier** [comment]
Hey @ngupta23 ,

Here is an example of the creation of the `S_df` constraints dataframe:
https://nixtla.github.io/hierarchicalforecast/examples/introduction.html

**Comment by ngupta23** [comment]
Awesome. Thank you so much!
