### ISSUE TITLE
Forecast indices do do not honor input index frequency

### ISSUE THREAD

**Issue by ngupta23** [Nixtla/hierarchicalforecast#158]
**Reproducible Code for this issue can be found here: https://gist.github.com/ngupta23/8adf65543584632f8ec57a27d9ec3480. It is based on the introductory notebook provided by Nixtla with a few changes.**

In this example, the forecast indices do not match the input indices. Input is Month-Start, Forecast produces Month-End. 

Below, the test data is for 2005-03-01 and 2005-04-01, but the forecasts are for 2005-02-28 and 2005-03-31 instead.

Note that the in-sample frequency seems to be ok.

![image](https://user-images.githubusercontent.com/33585645/211652186-d2cd3c5d-f162-47f5-8bcf-e5133cb79f44.png)

![image](https://user-images.githubusercontent.com/33585645/211652378-38e50596-883a-4de2-a682-60575535aae7.png)

**Comment by jmoralez** [comment]
Hey @ngupta23, sorry for the late reply. I believe this is due to the `freq` argument of statsforecast, `M` is month end. Can you try with `freq='MS'` (month start)?
