### ISSUE TITLE
Reconciliation is not adding up exactly.

### ISSUE THREAD

**Issue by ngupta23** [Nixtla/hierarchicalforecast#159]
**Reproducible Code for this issue can be found here: https://gist.github.com/ngupta23/8adf65543584632f8ec57a27d9ec3480. It is based on the introductory notebook provided by Nixtla with a few changes.**

In this example, 

There is no change to State 1 and State 2 inputs when doing BottomUp reconciliation for ETS. But at the top level (Australia), there is a slight adjustment. What would be the reason for this adjustment?

![image](https://user-images.githubusercontent.com/33585645/211653450-db2f4d6e-06c9-49a9-a9bc-8fa7620505e2.png)

**Comment by kdgutier** [comment]
Thanks for pointing this @ngupta23,
 
We are transforming the original inputs from `numpy 64` to `numpy 32` representation:
- https://github.com/Nixtla/hierarchicalforecast/blob/main/hierarchicalforecast/core.py#L214
- https://github.com/Nixtla/hierarchicalforecast/blob/main/hierarchicalforecast/core.py#L229


We are aware of this difference in the thousand round error, that is considered in the unit tests:
- https://github.com/Nixtla/hierarchicalforecast/blob/main/nbs/core.ipynb
