### ISSUE TITLE
Plan for unit tests

### ISSUE THREAD

**Issue by ngupta23** [Nixtla/hierarchicalforecast#160]
@FedericoGarza and team

I am curious to understand the plan to add unit tests for the Nixtla libraries (hierarchicalforecast, statsforecast, etc). I see that the development is done using some sort of [notebook exports](https://github.com/Nixtla/hierarchicalforecast/tree/main/nbs), but I do not see any corresponding unit tests or regression tests in the repo. Is there a plan to add such tests?

Thanks!

Note: The question came to mind after filing #158  and #159.

**Comment by ngupta23** [comment]
I might have been mistaken. It looks like the tests are embedded at the bottom of the notebook itself. Please ignore this issue if they are sufficient to test the library.

**Comment by kdgutier** [comment]
> I might have been mistaken. It looks like the tests are embedded at the bottom of the notebook itself. Please ignore this issue if they are sufficient to test the library.

yep, the all the notebooks that we export to the library have embedded unit tests.
