### ISSUE TITLE
minimal example not working

### ISSUE THREAD

**Issue by blazespinnaker** [Nixtla/hierarchicalforecast#161]
NameError: name 'HierarchicalData' is not defined

**Comment by blazespinnaker** [comment]
ModuleNotFoundError: No module named 'datasetsforecast'

**Comment by kdgutier** [comment]
Hi @blazespinnaker,

Would you be able to share the link of the broken example?
In the meantime these are the lines to get access to the `HierarchicalData` loader.
```
!pip install -U numba statsforecast datasetsforecast
```

```
from datasetsforecast.hierarchical import HierarchicalData, HierarchicalInfo
```

And here is an usage example: https://nixtla.github.io/hierarchicalforecast/examples/tourismlarge-evaluation.html

**Comment by melopeo** [comment]
I think this is fixed in the queueing PR https://github.com/Nixtla/hierarchicalforecast/pull/157
