### ISSUE TITLE
No such file or directory in datasetsforecast.hierarchical

### ISSUE THREAD

**Issue by kalsouza** [Nixtla/hierarchicalforecast#177]
I'm unable to use the code in the introduction to this package as I cannot get the dataset. This line:

Y_df, S_df, tags = HierarchicalData.load('./data', 'Wiki2')

Gives the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'data\\hierarchical\\Wiki2\\agg_mat.csv'

**Comment by kalsouza** [comment]
Python 3.9.12, windows

**Comment by FedericoGarza** [comment]
Thank you @kalsouza! Glad to hear that. To have a reference, what version solved the issue?
