### ISSUE TITLE
Non-Negative MinTrace hangs forever

### ISSUE THREAD

**Issue by candalfigomoro** [Nixtla/hierarchicalforecast#178]
Using the same data (unfortunately I can't share it), standard MinTrace performs the reconciliation in about 1 minute, while Non-Negative MinTrace (`MinTrace(method="ols", nonnegative=True)`) keeps running after hours (basically it hangs forever).

hierarchicalforecast 0.3.0

Do you have any hints on how I could debug the issue? Thanks

**Comment by iamyihwa** [comment]
Having similar issue.

**Comment by kdgutier** [comment]
Hey @iamyihwa and @candalfigomoro,

There is work to be merged that greatly improves the computational efficiency of the `MinTrace` method.

In between if you are interested in non-negative coherent predictions I suggest you to take a look to the `HINT` method we recently added to the NeuralForecast library. You can combine non-negative distributions (Poisson, NegativeBinomial, Tweedie, PoissonMixture) and BottomUp or MinTrace type reconciliations.

- [HINT Usage Example](https://nixtla.github.io/neuralforecast/examples/hierarchicalnetworks.html)
- [Distribution Losses Catalog](https://nixtla.github.io/neuralforecast/losses.pytorch.html#distributionloss)

**Comment by iamyihwa** [comment]
Sure will do Thanks @kdgutier !!!

**Comment by candalfigomoro** [comment]
@kdgutier Looks cool!

Unfortunately with my current forecasting problem, reconciliation with MinTrace or BottomUp doesn't seem to work well and the only reconciliation method that seems to work well in my specific case seems to be MiddleOut (lower levels are very intermittent so a top-down method from an intermediate level works better, while a bottom-up method works better for higher levels which are otherwise underestimated by NHITS).

Are there any plans to integrate other reconciliation methods into HINT?

**Comment by elephaint** [comment]
Non-negative mint is generally slower due to the requirement to solve a quadratic optimization problem.

I'd suggest to use a [sparse MinT method](https://nixtlaverse.nixtla.io/hierarchicalforecast/methods.html), which runs significantly faster.

As for the last question, not at the moment.
