### ISSUE TITLE
forecast_fitted_values() with neuralforecast estimators

### ISSUE THREAD

**Issue by candalfigomoro** [Nixtla/hierarchicalforecast#179]
In this example https://nixtla.github.io/hierarchicalforecast/examples/australiandomestictourism.html#computing-base-forecasts

```
fcst = StatsForecast(df=Y_train_df, 
                     models=[ETS(season_length=4, model='ZZA')], 
                     freq='QS', n_jobs=-1)
Y_hat_df = fcst.forecast(h=8, fitted=True)
Y_fitted_df = fcst.forecast_fitted_values()
```

you call `fcst.forecast_fitted_values()`, however the `forecast_fitted_values()` method seems to be unavailable for [neuralforecasts](https://github.com/nixtla/neuralforecast) estimators such as NHITS and NBEATSx.

Moreover, it looks like using Y_df is not enough, see https://github.com/Nixtla/hierarchicalforecast/issues/162

How can we get the expected Y_fitted_df data with neuralforecast estimators? Thanks

**Comment by jmoralez** [comment]
Hey @candalfigomoro. We have an example on how to use neural and mlforecast estimators [here](https://nixtlaverse.nixtla.io/hierarchicalforecast/examples/mlframeworksexample.html#4-reconcile-predictions). Can we close this issue?
