### ISSUE TITLE
Using Deep Learning Methods

### ISSUE THREAD

**Issue by baniasbaabe** [Nixtla/hierarchicalforecast#219]
### Description

Not specifically a feature request, but I was wondering if it makes sense to use Deep Learning Methods (e.g. neuralforecast or GluonTS) for Forecasting all the time series on all hierarchies  instead using StatsForecast (classical Methods) before reconcilation. 

The format of the Training Dataset for the Deep Learning model would be identical:

```

unique_id | ds                | y
total         | 01-01-2022 | 33
total         | 02-01-2022 | 10
total         | 03-01-2022 | 20
...
TX_TX1    | 01-01-2022 | 2
```

**Comment by kdgutier** [comment]
Hey @baniasbaabe,

Here is a tutorial on the reconciliation of ML-based forecasting methods:
- https://nixtla.github.io/hierarchicalforecast/examples/mlframeworksexample.html
- https://nixtla.github.io/hierarchicalforecast/examples/hierarchicalforecast-gluonts.html

And if you are interested in completely specialized neural forecasting architectures, check the work from the HINT method:
- https://nixtla.github.io/neuralforecast/examples/hierarchicalnetworks.html
