### ISSUE TITLE
Test sets includes y as defined

### ISSUE THREAD

**Issue by ArnMrchl** [Nixtla/hierarchicalforecast#222]
Hi,
Great package and tuto.

Minor issue, in **Split Train/Test sets** `Y_test_df` has `y` as a column (it should not).
If I drop `y`  (`Y_test_df.drop(columns=['y'], inplace=True)`)  it's OK but then the evaluation does not run.

**Comment by elephaint** [comment]
`Y_test_df` should have the ground truth value `y`, as it's our testing set.

We train using `y` in `Y_train_df`, and then we compare against the ground truth value of `y` in `Y_test_df`
