### ISSUE TITLE
Exception: min_trace (wls_var) needs covariance matrix to be positive definite.

### ISSUE THREAD

**Issue by vinaybridge** [Nixtla/hierarchicalforecast#223]
### What happened + What you expected to happen

All min_trace methods are throwing this issue for me 

### Versions / Dependencies

Latest version : 202307

### Reproduction script

```
  reconcilers = [BottomUp() , MinTrace(method="wls_var")]

  hrec = HierarchicalReconciliation(reconcilers=reconcilers)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by kdgutier** [comment]
Hey @vinaybridge,

You can use MinTrace's `mint_shr_ridge` parameter to help with the invertibility of the covariance matrix:
https://nixtla.github.io/hierarchicalforecast/methods.html#mintrace

Another strategy to improve the covariance's invertibility is to use a bit of random noise in the series. 
See the `FavoritaHierarchicalDataset.load_item_data` normal noise example:
https://github.com/Nixtla/hierarchicalforecast/blob/main/experiments/hierarchical_baselines/nbs/run_favorita_baselines.ipynb

**Comment by vinaybridge** [comment]
Not able to import it, Can you share template code for `MinTraceSparse` ?
