### ISSUE TITLE
[utils]  aggregate doesn't work correctly with most recent version of the code

### ISSUE THREAD

**Issue by iamyihwa** [Nixtla/hierarchicalforecast#224]
### What happened + What you expected to happen

Hi, 
Thanks for adding sparse versions of the reconcile methods and S matrix.
aggregate() function however doesn't seem to work correctly. It doesn't seem to do the balancing (numpy_balance), and neither creating the aggregated time series based on spec. 

pip version: (previous version)
<img width="342" alt="image" src="https://github.com/Nixtla/hierarchicalforecast/assets/12494156/0be1146f-66a8-4b84-a8e6-d34219362f7d">

main branch: 
<img width="557" alt="image" src="https://github.com/Nixtla/hierarchicalforecast/assets/12494156/a237e39c-3276-419a-823e-2d8f91b5094d">

### Versions / Dependencies

main branch 

### Reproduction script

 Code to reproduce the result : 
```
df = pd.DataFrame(data = {'cat1': ['a', 'a', 'a'], 'cat2': ['1', '2', '3'],
                         'y': [10, 20, 30], 'ds': ['2020-01-01', '2020-02-01', '2020-03-01']})
df.insert(0, 'country', 'COUNTRY')

spec = [['country'], ['country', 'cat1'], ['country','cat1', 'cat2']]

Y_df, S_df, tags = aggregate(df, spec)
Y_df

``` 

### Issue Severity

None

**Comment by candalfigomoro** [comment]
Related issue https://github.com/Nixtla/hierarchicalforecast/issues/211 ?
