### ISSUE TITLE
dependency on `quadprog`

### ISSUE THREAD

**Issue by twobitunicorn** [Nixtla/hierarchicalforecast#256]
### What happened + What you expected to happen

Executing `pip install hierarchicalforecast` on `python=3.11.6` (Mac, M2) fails building with `quadprog` identified as the failure.  A fix for the issue is in this [branch](https://github.com/quadprog/quadprog/pull/43) .  However, it seems that the project is looking for [maintainers](https://github.com/quadprog/quadprog/issues/41).

### Versions / Dependencies

`quadprog`

### Reproduction script

`mamba create -n nixtla python=3.11.6 -c conda-forge`
`pip install hierarchicalforecast`

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by mnajaria** [comment]
It also failed on Windows 10, I checked some links but still unable to fix it. Here is the error:

Building wheels for collected packages: quadprog
  Building wheel for quadprog (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for quadprog (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'quadprog' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quadprog
Failed to build quadprog
ERROR: Could not build wheels for quadprog, which is required to install pyproject.toml-based projects

**Comment by mnajaria** [comment]
I also tried to get the wheel from the pypi but it didn't have it for Python 3.11.

**Comment by hmanz** [comment]
In case it's useful to anyone, you can use this temporary workaround in the meantime. Before installing hierarchicalforecast, first install this version of quadprog: `pip install git+https://github.com/quadprog/quadprog.git@refs/pull/43/head`

**Comment by leassis91** [comment]
@hmanz thank you so much bro <3

**Comment by jmoralez** [comment]
[quadprog 0.1.12](https://pypi.org/project/quadprog/0.1.12/#files) includes wheels for CPython 3.8-3.12 and for the most common operating systems. Feel free to reopen if you encounter this issue again.

**Comment by twobitunicorn** [comment]
thank you !  appreciate the work
