### ISSUE TITLE
[Methods] Undesired conversion to a dense matrix 

### ISSUE THREAD

**Issue by nulam** [Nixtla/hierarchicalforecast#261]
### What happened + What you expected to happen

Current implementation of `BottomUpSparse` reconciliation method causes an undesired conversion to a dense matrix, potentially leading to an OOM on large datasets. The lack of speedup was already observed before as noted in makoren's comment in the class definition.

The culprit is the `idx_bottom` indexed assignment:
https://github.com/Nixtla/hierarchicalforecast/blob/2296c259542dbd906cfba4b8345c3b72148dad79/hierarchicalforecast/methods.py#L249

Locally I managed to fix it by replacing this line with the following

```python
for idx in idx_bottom:
    P[idx] = S.getrow(idx)
```

However, the performance is quite suboptimal, but it's sufficient for my use case, hence I would rather raise this issue than create a PR :)

### Versions / Dependencies

hierarchicalforecast==0.4.1

### Reproduction script

using an S matrix with n>200k leads to OOM with BottomUpSparse reconciliation

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by mcsqr** [comment]
@nulam Thanks for using this! Why don't you open a PR, I haven't worked on this recently but I'll have a look (I now got my hands on 200k dataset as well), and then hopefully someone from nixtla finds the time to check if they have any problem with idx_bottom or anything else.

**Comment by AzulGarza** [comment]
hey @nulam and @mcsqr! currently, the efforts to remove the `idx_bottom` are paused. would you like to open a PR with your improvements, @nulam?❤️

**Comment by nulam** [comment]
Solved by #276
