### ISSUE TITLE
KeyError when trying to get prediction intervals with MiddleOut

### ISSUE THREAD

**Issue by pkwan9** [Nixtla/hierarchicalforecast#262]
This following error pops up when I try to get prediction intervals with MiddleOut.  It doesn't show up if I use other reconciliation methods.

 `  File "<....>/hierarchicalforecast/core.py", line 313, in reconcile
    sorted_quantiles = np.reshape(fcsts_model['quantiles'], (len(Y_tilde_df),-1))
KeyError: 'quantiles'`

**Comment by elephaint** [comment]
Same as #168, closing this one.
