### ISSUE TITLE
Package does not work with 3.12

### ISSUE THREAD

**Issue by Spen-D** [Nixtla/hierarchicalforecast#266]
### What happened + What you expected to happen

ModuleNotFoundError: No module named 'distutils'. Some packages got depreciated in 3.12 that are causing issues.

### Versions / Dependencies

Python 3.12.2, Windows 10

### Reproduction script

pip install hierarchicalforecast

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
We don't use `distutils` in this package. Can you provide the full stacktrace?

**Comment by d-vasek** [comment]
I think the reason is that you don't support newer version of numpy. You require version of numpy < 1.24, but those versions of numpy require distutils, and only version 1.26 and above of numpy work with python 3.12. Would be great to increase it.
