### ISSUE TITLE
Support newer numpy versions

### ISSUE THREAD

**Issue by DManowitz** [Nixtla/hierarchicalforecast#270]
### Description

This library is currently limited to `numpy <1.24`.  However, numpy 1.24 was released more than 1.5 years ago.  It seems that this package should aim to support a least one or two newer versions of numpy than it currently supports, even if it is not quite ready for numpy 2.0 (which was recently released).

### Use case

Supporting newer numpy versions allows this library to be used with newer versions of other libraries that may need newer numpy versions.

**Comment by jmoralez** [comment]
Hey @DManowitz, thanks for raising this. It seems that pin was to fix a compatibility error a long time ago (#142), I believe we can remove that pin now, would you like to make that change? It'd just be removing the upper bound here https://github.com/Nixtla/hierarchicalforecast/blob/88fa68a7694aac82f8c8ca6f0d7c6e68217bb425/settings.ini#L18

**Comment by DManowitz** [comment]
@jmoralez I could remove that pin, but I'm not quite sure from that other issue if the problem was actually present in a GA version of numpy 1.24.0 or a RC version.  Also, someone should probably test against at least the most recent pre-2.0 version of numpy and numpy 2.0, now that it is GA.  I don't know if I have the bandwidth do do that at the moment, but I might.

**Comment by jmoralez** [comment]
You can open a PR and see if the CI passes. If it doesn't I can work through the required changes.

**Comment by jmoralez** [comment]
Fixed by #272
