### ISSUE TITLE
Probabilistic Forecast Reconciliation

### ISSUE THREAD

**Issue by Manjubn777** [Nixtla/hierarchicalforecast#31]
After going through the package and paper found that supports only point forecasts reconciliation. I would like to know if it supports probabilistic forecast reconciliation. I appreciate your quick response to my inquiry for information.

**Comment by kdgutier** [comment]
Hi @Manjubn777,

We have been doing research/working on probabilistic hierarchical forecasting, but have not released.

I can point you to my work in progress paper ["Probabilistic Hierarchical Forecasting with Deep Poisson Mixtures"](https://arxiv.org/pdf/2110.13179.pdf) and [Taieb's PERMBU](https://proceedings.mlr.press/v70/taieb17a.html).

Regarding implementations of algorithms GluonTS team did an effort to improve the usability of [PERMBU in this repository](https://github.com/rshyamsundar/gluonts-hierarchical-ICML-2021/blob/a822a9d7c571e20ef2e1d554e6a678c2404ee2b3/src/gluonts/model/r_forecast/R/hierarchical_methods.R#L245), it has a lot of dependency frictions.

If you have any pointers please let me know, this is a really interesting topic for us.

**Comment by FedericoGarza** [comment]
Hey @Manjubn777! The new version of `HierarchicalForecast` supports probabilistic forecast reconciliation. 

- [Example assuming normality](https://nixtla.github.io/hierarchicalforecast/examples/australiandomestictourism-intervals.htmll).
- [Example using bootstrapping](https://nixtla.github.io/hierarchicalforecast/examples/australiandomestictourism-bootstraped-intervals.html)

**Comment by Manjubn777** [comment]
Hey Team,
Thank you so much for notebooks and I do have a question. Let's say I have
2000 forecast samples for each day,which will be passed as y_hat_df and I
have actuals which is like one value for each day(daily data)., I will pass
actual data as fitted values. setting bootstrap = True helps me reconcile?

I would appreciate your answer to the above question.

Thanks and Regards,
Manjula
