### ISSUE TITLE
Optimal Combination Reconciliation

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/hierarchicalforecast#32]
From the search of other available reconciliation methods. It seems that we are still lacking the ones from 
["George Athanasopoulos, Rob J. Hyndmanm Roman Ahmed, and Lin Shang. Optimal combination forecasts for hierarchical"](https://www.researchgate.net/publication/227358866_Optimal_combination_forecasts_for_hierarchical).

I would like to confirm.

**Comment by FedericoGarza** [comment]
Fixed in #36.
