### ISSUE TITLE
Pls update the Jupyter example notebook

### ISSUE THREAD

**Issue by arjuns2020** [Nixtla/hierarchicalforecast#43]
Hi the google colab notebook is not available.. Kindly update it

The 'Nixtla/hierarchicalforecast' repository doesn't contain the 'examples/TourismSmall.ipynb' path in 'main'.

**Comment by FedericoGarza** [comment]
hi @arjuns2020!

Thanks for letting us know about the problem. We are fixing it. In the meantime, you can find that example [here](https://nixtla.github.io/hierarchicalforecast/examples/TourismSmall.html).

**Comment by FedericoGarza** [comment]
The examples directory now lives in `nbs/examples/`. The notebook is [here](https://github.com/Nixtla/hierarchicalforecast/blob/main/nbs/examples/TourismSmall.ipynb).

**Comment by FedericoGarza** [comment]
Fixed in #44. :)
