### ISSUE TITLE
Wrong documentation at PyPI

### ISSUE THREAD

**Issue by cmcouto-silva** [Nixtla/hierarchicalforecast#45]
Kindly update the example in the "How to use" section at the [PyPI website](https://pypi.org/project/hierarchicalforecast/), as well as the link to the Colab Notebook. 

I've been stuck in that non-working example, but here in the repo, I found the correct one. You have developed a fantastic package, but folks like me who first face the PyPI documentation might find it not working while it is (with updated code).

The main issue I found at PyPI is using `auto_arima` and `naive` instead of `AutoARIMA` and `Naive`.

Thanks for your contribution =D

**Comment by FedericoGarza** [comment]
Hi @cmcouto-silva! :)

Thanks for reporting the issue. We haven't released a new version on pypi, but you can find the documentation with the updated code here: https://nixtla.github.io/hierarchicalforecast/.

**Comment by cmcouto-silva** [comment]
The last PyPI library version is 0.0.6 and it already doesn't have `auto_arima` and `naive`. I installed the library using pip and I couldn't use the PyPI example, but I could use it successfully with the updated code you posted. Thanks for the quick response.

**Comment by FedericoGarza** [comment]
The new release (https://pypi.org/project/hierarchicalforecast/) includes the new syntax of `StatsForecast`. :)
