### ISSUE TITLE
h Indexing in evaluate method

### ISSUE THREAD

**Issue by jakebajo** [Nixtla/hierarchicalforecast#46]
In the `.evaluate`  of the `HierarchicalEvaluation` class, it sets `h = len(Y_h.loc[Y_h.index[0]])` but when the look ahead period is only 1 period ahead, `Y_h.loc[Y_h.index[0]]` returns values rather than a dataframe.

The length of these values is then 2 because of the ds column and the forecast column. This then returns an error during the reshape of Y_test here: `y_test_cats = Y_test.loc[cats, 'y'].values.reshape(-1, h)` because it tries to reshape to 2 even though there is only 1 record.

Would changing  `h = len(Y_h.loc[Y_h.index[0]])` to  `h = len(Y_h.loc[[Y_h.index[0]]])` with the double brackets to ensure a dataframe is returned work?

Let me know if you need any additional detail or a reproducible example as this is my first issue statement

**Comment by FedericoGarza** [comment]
Hi @jakebajo! 

Thank you for explaining the issue. It's clear to me, and your solution should work. We'll be fixing the problem asap. :)

**Comment by jakebajo** [comment]
Sounds great thank you!
