### ISSUE TITLE
OptimalCombination pip import error

### ISSUE THREAD

**Issue by dluuo** [Nixtla/hierarchicalforecast#50]
Hello, when I call pip install hierarchicalforecast and then try to import the OptimalCombination class I get an import error.
I was able to fix this issue but calling pip install git+https://github.com/Nixtla/hierarchicalforecast to import the newest version of the repo, so I think the pip is not up to date with the latest version of the repo.

**Comment by FedericoGarza** [comment]
Hey @dluuo!

Thanks for reporting the issue. We'll be releasing a new version of HierarchicalForecast to include `OptimalCombination` and another improvement in the next week. :)

**Comment by FedericoGarza** [comment]
Hey @dluuo! The new version of HierarchicalForecast is now released (https://pypi.org/project/hierarchicalforecast/)
