### ISSUE TITLE
Probabilistic Coherent Predictions `PERMBU`, `Bootstrap` or `MinTrace-normality` compatibility

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/hierarchicalforecast#74]
Let's reevaluate the `bootstrap` boolean parameter from the `core.HierarchicalForecast` main class to `prob_method` that accepts strings to be able to use `PERMBU`, `Bootstrap` or `MinTrace-normality`. 

We need to think of a way to make the methods compatible between one-another or to declare a new ProbabilisticReconciler class.

**Comment by FedericoGarza** [comment]
Fixed in #83
