### ISSUE TITLE
MinT improved computational efficiency

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/hierarchicalforecast#75]
By recommendation of Shanika, we can change the current matrix:
$P_{MinT} = (SW^{−1} S)^{-1}S^{t} W^{−1}$

To avoid the double computation of the inverses that scale cubically.
Her [paper](https://robjhyndman.com/publications/mint/) contains the alternative that uses a single inverse with lower dimensionality.

**Comment by elephaint** [comment]
This has been addressed in a.o. #264
