### ISSUE TITLE
Small data set size issue

### ISSUE THREAD

**Issue by arjuns2020** [Nixtla/hierarchicalforecast#76]
##########################Getting this error#####################

RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/dist-packages/statsforecast/core.py", line 154, in forecast
    raise error
  File "/usr/local/lib/python3.7/dist-packages/statsforecast/core.py", line 149, in forecast
    res_i = model.forecast(h=h, y=y_train, X=X_train, X_future=X_f, fitted=fitted, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/statsforecast/models.py", line 481, in forecast
    mod = ets_f(y, m=self.season_length, model=self.model)
  File "/usr/local/lib/python3.7/dist-packages/statsforecast/ets.py", line 968, in ets_f
    raise NotImplementedError('tiny datasets')
NotImplementedError: tiny datasets
"""

The above exception was the direct cause of the following exception:

NotImplementedError                       Traceback (most recent call last)
[<ipython-input-49-b74f830ba881>](https://localhost:8080/#) in <module>
      2                      models=[ETS(season_length=4, model='ZAA')],
      3                      freq='M', n_jobs=-1)
----> 4 Y_hat_df = fcst.forecast(h=4, fitted=True)
      5 Y_fitted_df = fcst.forecast_fitted_values()

**Comment by kdgutier** [comment]
Hi @arjuns2020,

Thanks for using the `HierarchicalForecast` library. It seems that the size of some of the series in your dataset might be smaller than the minimal amount of observations needed to fit `StatsForecast`'s ETS method.

To test the size's hypothesis try to change `models=[Naive()]`.

Additionally, you may want to check the size smallest series with `y_train.groupby('unique_id').size()`.

**Comment by FedericoGarza** [comment]
hey @arjuns2020! We recently released a new version of `StatsForecast` that includes the [`fallback_model`](https://nixtla.github.io/statsforecast/core.html#statsforecast) argument. If the main model throws an error, a safe model is fitted. 

Here's an example:

```python
fcst = SatstForecast(
     models=[ETS(season_length=4, model='ZAA')],
     freq='M', 
     n_jobs=-1,
     fallback_model=Naive() # fit this model in case of ETS failure
)
```
