### ISSUE TITLE
Wrong order of arguments in README tutorial

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/hierarchicalforecast#81]
### Discussed in https://github.com/Nixtla/hierarchicalforecast/discussions/80

<div type='discussions-op-text'>

<sup>Originally posted by **stefanhuber1510** October 19, 2022</sup>
The last line of the first big block of the tutorial on the readme file is the following:

Y_rec_df = hrec.reconcile(Y_hat_df, Y_df_train, S, tags)

It seems to me that, Y_df_train is in the wrong position here, and should come after tags (since the arguments are positional and thus the order matters)</div>

**Comment by FedericoGarza** [comment]
Fixed in #84
