### ISSUE TITLE
Guaranteed hierarchical ordering for reconciliation methods inputs. 

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/hierarchicalforecast#82]
A clever way to simplify lower level reconciliation functions is to assume 'hierarchically ordered series'.
It can be achieved with the following lines at the beginning of the `reconcile` method on the `core.HierarchicalForecast` with these lines:
```
Y_df.unique_id = Y_df.unique_id.astype('category')
Y_df.unique_id = Y_df.unique_id.cat.set_categories(S_df.index)
```

If we decide to operate like this, we should add in the docstrings of the methods that are order dependent the assumption.
Currently the `PERMBU` method operates like this.

These two issues are closely related: [Challenging HierarchicalForecast method input's indexing](https://github.com/Nixtla/hierarchicalforecast/issues/58).

**Comment by FedericoGarza** [comment]
The lower-level methods assume that `y` arguments and `S` are hierarchically ordered. The `HierarchicalReconciliation` class ensures the inputs are properly ordered. See, for example,

https://github.com/Nixtla/hierarchicalforecast/blob/0a2d6c7bcaf1518b2ad1c657bbcab4fb03e7d061/hierarchicalforecast/core.py#L104

What is not assumed is that `S` is ordered in descending order (bottom series at the end).
