### ISSUE TITLE
[FEAT,BUG] Mismatch between `Y_df` and `S` outputted by `aggregate`

### ISSUE THREAD

**Issue by AzulGarza** [Nixtla/hierarchicalforecast#87]
In some cases, `utils.aggregate` returns a different order of `unique_id` in `Y_df` and `S`. Even though `core.HierarchicalReconciliation` ensures the same order, it could reduce a good user experience.

**Comment by elephaint** [comment]
Doesn't seem still present in main, but order is guaranteed to be the same in aggregate function in #305
