### ISSUE TITLE
Verbose/TQDM Progress when calling reconcile()

### ISSUE THREAD

**Issue by renanklehm** [Nixtla/hierarchicalforecast#95]
I followed the tutorial, and everything worked until I reached the following part:

`reconcilers = [
    BottomUp(),
    TopDown(method='forecast_proportions'),
    MiddleOut(middle_level='filial/categoria',
              top_down_method='forecast_proportions')]
hrec = HierarchicalReconciliation(reconcilers=reconcilers)
Y_rec_df = hrec.reconcile(Y_hat_df=Y_hat_df, Y_df=Y_train_df, 
                          S=S, tags=tags)`

It works fine in small datasets, but I'm trying to use this in a dataset with the following structure:

Filial (36 unique)
----Categoria (50 unique)
--------Master(~30k unique)

Each series have 36 time steps.

The code is currently running the reconcile() function, it is stuck in this part for the last 2 hours. It would be nice if there was an indication of how long it will probably take or at least some sort of verbose showing of what is going on.

My computer has an i5-12500H, 16Gb of RAM, and an SSD for storage.

**Comment by kdgutier** [comment]
Hi @renanklehm,

Thanks a lot for raising this issue. We are improving the reconciliation methods speed.

You might want to try the new version installing from this branch:
```
!pip install git+https://github.com/Nixtla/hierarchicalforecast.git@fast_topdown_bottomup
```

We will include them soon in the main library.

**Comment by elephaint** [comment]
To add to this two years later, we also have [sparse methods](https://nixtlaverse.nixtla.io/hierarchicalforecast/methods.html) now.
