### ISSUE TITLE
ERM stationarity warning

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/hierarchicalforecast#98]
In the presence of non stationarity `ERM` might degrade in performance.
It would be a good idea to add a test, and a warning for the user if the series are non-stationary.

**Comment by elephaint** [comment]
ERM generally performs quite poorly, and the regularized versions are more or less unusable in settings of any size. I'd personally not want to spend too much time improving ERM, as I'd be very surprised if anyone would actually use this method in practice.

Happy to be convinced otherwise, though.
